format_version: v1.0
type: UniqueComponent
attributes: {id: a_i2s2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: I2S_BAUD_RATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '48000'}
  - type: Integer
    attributes: {id: I2S_BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: a_i2s2, value: '1'}
  - type: KeyValueSet
    attributes: {id: I2S_LRCLK_PIN_DEFINE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '66'}
  - type: Integer
    attributes: {id: I2S_MCLK_BCLK_RATIO}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: KeyValueSet
    attributes: {id: I2S_SPICON_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: SPI2_I2S}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: a_drv_i2s_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2s_I2S_dependency}
- type: ElementPosition
  attributes: {x: '43', y: '281', id: a_i2s2}
