format_version: v1.0
type: UniqueComponent
attributes: {id: audio_codec_ak4954}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: DRV_AK4954_AUDIO_DATA_FORMAT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: Integer
    attributes: {id: DRV_AK4954_BAUD_RATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '48000'}
  - type: String
    attributes: {id: DRV_AK4954_I2C}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: audio_codec_ak4954, value: DRV_I2C_0}
  - type: String
    attributes: {id: DRV_AK4954_I2C_INDEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: audio_codec_ak4954, value: DRV_I2C_INDEX_0}
  - type: String
    attributes: {id: DRV_AK4954_I2S}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: audio_codec_ak4954, value: DRV_I2S_0}
  - type: String
    attributes: {id: DRV_AK4954_I2S_INDEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: audio_codec_ak4954, value: DRV_I2S_INDEX_0}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: DRV_I2C}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_i2c_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2c}
  - type: DirectDependency
    attributes: {id: DRV_I2S}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: a_drv_i2s_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2s}
- type: ElementPosition
  attributes: {x: '404', y: '195', id: audio_codec_ak4954}
