format_version: v1.0
type: UniqueComponent
attributes: {id: lib_wolfcrypt}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: cryptoCrya_03710}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'false'}
  - type: Boolean
    attributes: {id: cryptoCrya_U2803}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'false'}
  - type: Boolean
    attributes: {id: cryptoCrya_U2805}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'false'}
  - type: Combo
    attributes: {id: wolfSslRTOSSupport}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: FreeRTOS}
  - type: Boolean
    attributes: {id: wolfcrypt_dh}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_hkdf}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_hmac}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_random}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'true'}
  - type: Combo
    attributes: {id: wolfcrypt_rsaKeySize}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 4096 bits}
  - type: Boolean
    attributes: {id: wolfcrypt_rsaPss}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_sha384}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_sha512}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfssl_included}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'false'}
- type: ElementPosition
  attributes: {x: '428', y: '388', id: lib_wolfcrypt}
