configName: sam_e54_cult_freertos
folderName: sam_e54_cult_freertos
format_version: v1.0
frameworkPath: ..\..\..\..\harmony_github
processor: ATSAME54P20A
projectName: sam_e54_cult_freertos
settings:
  PackageFilter: audio;bootloader;bootloader_apps_uart;bsp;core;core_apps_sam_d5x_e5x;crypto;csp;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_l10_l11;gfx;gfx_apps;MPLAB-Harmony-Reference-Apps;net;net_apps_sam_e5x;net_apps_sam_e70_v71;quick_docs;quick_docs_old_version;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.5.87\atdf\ATSAME54P20A.atdf
