format_version: v1.0
type: UniqueComponent
attributes: {id: adc1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ADC_CALLBACK_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_CallbackRegister}
  - type: String
    attributes: {id: ADC_CHANNEL_SELECT_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_ChannelSelect}
  - type: String
    attributes: {id: ADC_CH_PHASE_U}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC_POSINPUT_AIN0}
  - type: String
    attributes: {id: ADC_CH_PHASE_V}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC_POSINPUT_AIN0}
  - type: String
    attributes: {id: ADC_CH_POT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC_POSINPUT_AIN0}
  - type: String
    attributes: {id: ADC_CH_VDC_BUS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC_POSINPUT_AIN0}
  - type: Combo
    attributes: {id: ADC_CONV_TRIGGER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: HW Event Trigger}
  - type: Boolean
    attributes: {id: ADC_CTRLA_ONDEMAND}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADC_CTRLA_PRESCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: ADC_CTRLA_RUNSTDBY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADC_CTRLB_WINMODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: ADC_EVCTRL_FLUSH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADC_EVCTRL_START}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: String
    attributes: {id: ADC_GET_RESULT_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_ConversionResultGet}
  - type: String
    attributes: {id: ADC_GND}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC_NEGINPUT_GND}
  - type: KeyValueSet
    attributes: {id: ADC_INPUTCTRL_MUXPOS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Boolean
    attributes: {id: ADC_INTENSET_WINMON}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: ADC_INT_CLEAR_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_InterruptsClear}
  - type: String
    attributes: {id: ADC_INT_DISABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_InterruptsDisable}
  - type: String
    attributes: {id: ADC_INT_ENABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_InterruptsEnable}
  - type: String
    attributes: {id: ADC_IS_RESULT_READY_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_ConversionStatusGet}
  - type: Integer
    attributes: {id: ADC_SAMPCTRL_SAMPLEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Comment
    attributes: {id: ADC_SAMPCTRL_SAMPLEN_TIME}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Conversion Time is 26.0 uS ****'}
  - type: String
    attributes: {id: ADC_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_Enable}
  - type: String
    attributes: {id: ADC_START_CONV_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_ConversionStart}
  - type: String
    attributes: {id: ADC_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_Disable}
  - type: Boolean
    attributes: {id: ADC_WINDOW_OUTPUT_EVENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: ADC_WINLT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '3000'}
  - type: Integer
    attributes: {id: ADC_WINUT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: String
    attributes: {id: INTERRUPT_ADC_RESULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_RESRDY_IRQn}
- type: ElementPosition
  attributes: {x: '148', y: '219', id: adc1}
