format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_usart}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_USART_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usart, value: Synchronous}
  - type: File
    attributes: {id: USART_ASYNC_LOCAL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: USART_ASYNC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: USART_SYNC_LOCAL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: USART_SYNC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_usart}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: DRV_USART_CLIENTS_NUM}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '3'}
      - type: String
        attributes: {id: DRV_USART_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_0, value: SERCOM3}
      - type: Integer
        attributes: {id: DRV_USART_QUEUE_SIZE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
      - type: Integer
        attributes: {id: DRV_USART_RX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_0, value: '-1'}
      - type: Integer
        attributes: {id: DRV_USART_TX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_0, value: '-1'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_usart_UART_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: sercom3}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: SERCOM3_UART}
- type: ElementPosition
  attributes: {x: '157', y: '343', id: drv_usart}
