format_version: v1.0
type: UniqueComponent
attributes: {id: HarmonyCore}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: APP0_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: APP0_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: APP1_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: app_live_update.c}
  - type: File
    attributes: {id: APP1_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: app_live_update.h}
  - type: File
    attributes: {id: CONFIGURATION_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_APP_FILE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'false'}
      - type: User
        attributes: {value: 'true'}
  - type: File
    attributes: {id: GEN_APP_TASKS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: GEN_APP_TASK_CONF_MENU0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: GEN_APP_TASK_CONF_MENU1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: GEN_APP_TASK_COUNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Menu
    attributes: {id: GEN_APP_TASK_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: GEN_APP_TASK_NAME_1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: app_live_update}
  - type: File
    attributes: {id: TASKS_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: USER_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '133', y: '73', id: HarmonyCore}
