files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_live_update.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 64D0F9C57F1452BD074A574237B811D7
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64D0F9C57F1452BD074A574237B811D7
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_ef_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: 94FEAAD355F33763AC84D67402D4D7F3
  logicalPath: config/pic32mz_ef_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 94FEAAD355F33763AC84D67402D4D7F3
- generatedChecksum: 1FE8F55543D36A22F134CFADBB013A69
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1FE8F55543D36A22F134CFADBB013A69
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 5192896384BDEA0B08CDCE5833E31223
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5192896384BDEA0B08CDCE5833E31223
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mz_ef_sk/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: 01DCC998E5EE8CEEECE71AE87264A44F
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 01DCC998E5EE8CEEECE71AE87264A44F
- generatedChecksum: 085AD21E69A015135F99F9AE4E244A69
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 085AD21E69A015135F99F9AE4E244A69
- generatedChecksum: CA41C0116AA86AA82F796A658ADFE1E7
  logicalPath: config/pic32mz_ef_sk/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA41C0116AA86AA82F796A658ADFE1E7
- generatedChecksum: 926DC70EA512413BC1A9E3AFEE574CAE
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 926DC70EA512413BC1A9E3AFEE574CAE
- generatedChecksum: 05C3A7AE80B236FB79DCA8C36D499779
  logicalPath: config/pic32mz_ef_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 05C3A7AE80B236FB79DCA8C36D499779
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mz_ef_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_live_update.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: A9C595E0E5A92D2B85C18D2A27597B84
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: A9C595E0E5A92D2B85C18D2A27597B84
- generatedChecksum: 7A852268CAA1F0FBB9E75D327532882A
  logicalPath: config/pic32mz_ef_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A852268CAA1F0FBB9E75D327532882A
- generatedChecksum: C48A46B9D19DCE882C59D310626978A2
  logicalPath: config/pic32mz_ef_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: C48A46B9D19DCE882C59D310626978A2
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_ef_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 0EA600D4DBA17C02F74FD5C7BE8F56B0
  logicalPath: config/pic32mz_ef_sk/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 0EA600D4DBA17C02F74FD5C7BE8F56B0
- generatedChecksum: 3C465EE2268CD765C11300F75C6560CC
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C465EE2268CD765C11300F75C6560CC
- generatedChecksum: 4C730E56D028FBC00572DDBD3E67C7C7
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C730E56D028FBC00572DDBD3E67C7C7
- generatedChecksum: 42ECD2217FBCF58E950E691EEB8D7E11
  logicalPath: config/pic32mz_ef_sk/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: 42ECD2217FBCF58E950E691EEB8D7E11
- generatedChecksum: 86D499749C924875389705AA3D0C9FD7
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 86D499749C924875389705AA3D0C9FD7
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_ef_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: null
  logicalPath: config/pic32mz_ef_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
