configName: pic32mz_ef_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../../../harmony_github
processor: PIC32MZ2048EFH144
projectName: ''
settings:
  PackageFilter: audio;bootloader;bootloader_apps_uart;bsp;core;crypto;csp;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;gfx;gfx_apps;reference_apps;net;quick_docs;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.57\atdf\PIC32MZ2048EFH144.atdf
