format_version: v1.0
configName: sam_e51_cnano
folderName: sam_e51_cnano
frameworkPath: C:\h3
processor: ATSAME51J20A
projectName: sam_e51_cnano
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME51_DFP\3.6.130\atdf\ATSAME51J20A.atdf
