format_version: v1.0
type: UniqueComponent
attributes: {id: drvWifiWinc}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_WIFI_WINC1500_VERSION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 19.7.6}
  - type: Combo
    attributes: {id: DRV_WIFI_WINC_DRIVER_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Socket Mode}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_10}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_11}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_12}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_13}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_14}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_15}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_8}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_9}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Integer
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_SELECT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: '2'}
  - type: Combo
    attributes: {id: DRV_WIFI_WINC_LOG_LEVEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Inform}
  - type: String
    attributes: {id: DRV_WIFI_WINC_SPI_INST}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: drv_spi_0}
  - type: Integer
    attributes: {id: DRV_WIFI_WINC_SPI_INST_IDX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: '0'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_USE_SYS_DEBUG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: spi}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_spi_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_spi}
- type: ElementPosition
  attributes: {x: '230', y: '440', id: drvWifiWinc}
