format_version: v1.0
type: UniqueComponent
attributes: {id: eic}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: EIC_CHAN_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: EIC_CHAN_1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: EIC_CHAN_15}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: EIC_CHAN_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: EIC_CONFIG_FILTEN_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: EIC_CONFIG_FILTEN_1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: EIC_CONFIG_FILTEN_15}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: EIC_CONFIG_FILTEN_2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: EIC_CONFIG_SENSE_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: EIC_CONFIG_SENSE_1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: EIC_CONFIG_SENSE_15}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: EIC_CONFIG_SENSE_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Hex
    attributes: {id: EIC_EXTINTEO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '0'}
  - type: Hex
    attributes: {id: EIC_INT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '32772'}
  - type: Boolean
    attributes: {id: EIC_INT_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: EIC_INT_1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: EIC_INT_15}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: EIC_INT_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Menu
    attributes: {id: EIC_MENU15}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: EIC_MENU2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Hex
    attributes: {id: EIC_WAKEUP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '0'}
- type: ElementPosition
  attributes: {x: '190', y: '200', id: eic}
