format_version: v1.0
type: UniqueComponent
attributes: {id: tc2}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: COMPARE_SET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: TC2_Timer16bitCompareSet}
  - type: String
    attributes: {id: COUNTER_GET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: TC2_Timer16bitCounterGet}
  - type: String
    attributes: {id: PERIOD_SET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: TC2_Timer16bitPeriodSet}
  - type: String
    attributes: {id: SYS_TIME_COMPONENT_ID}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: sys_time}
  - type: String
    attributes: {id: SYS_TIME_PLIB_OPERATION_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: SYS_TIME_PLIB_MODE_COMPARE}
  - type: File
    attributes: {id: TC_CAPTURE_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: NON_SECURE}
  - type: File
    attributes: {id: TC_CAPTURE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: NON_SECURE}
  - type: File
    attributes: {id: TC_COMMON_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: NON_SECURE}
  - type: Long
    attributes: {id: TC_COMPARE_CC0}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
  - type: Long
    attributes: {id: TC_COMPARE_CC1}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '24'}
  - type: File
    attributes: {id: TC_COMPARE_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: NON_SECURE}
  - type: Long
    attributes: {id: TC_COMPARE_PERIOD}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
  - type: Comment
    attributes: {id: TC_COMPARE_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Compare Period is 512.0 us ****'}
  - type: File
    attributes: {id: TC_COMPARE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: NON_SECURE}
  - type: KeyValueSet
    attributes: {id: TC_CTRLA_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: TC_CTRLA_PRESCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '7'}
  - type: Integer
    attributes: {id: TC_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '46875'}
  - type: Comment
    attributes: {id: TC_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Timer resolution is 21333.3333333 nS****'}
  - type: File
    attributes: {id: TC_SYS_DEF}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_DEFINITIONS_H_INCLUDES}
  - type: File
    attributes: {id: TC_SYS_INT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_INIT_C_SYS_INITIALIZE_PERIPHERALS}
  - type: Boolean
    attributes: {id: TC_SYS_TIME_CONNECTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: 'true'}
  - type: File
    attributes: {id: TC_TIMER_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: NON_SECURE}
  - type: Boolean
    attributes: {id: TC_TIMER_INTENSET_MC1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: 'true'}
  - type: Boolean
    attributes: {id: TC_TIMER_INTENSET_OVF}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: 'false'}
      - type: User
        attributes: {value: 'true'}
  - type: Long
    attributes: {id: TC_TIMER_PERIOD}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '46'}
  - type: File
    attributes: {id: TC_TIMER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: NON_SECURE}
  - type: Float
    attributes: {id: TC_TIMER_TIME_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '1398.1013'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: TIMER_PERIOD_MAX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '65535'}
  - type: Integer
    attributes: {id: TIMER_WIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '16'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: TC2_TMR}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_time}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_time_TMR_dependency}
- type: ElementPosition
  attributes: {x: '171', y: '260', id: tc2}
