format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_maxtouch_controller}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_I2C_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_maxtouch_controller, value: Asynchronous}
  - type: Integer
    attributes: {id: DRV_MAXTOUCH_I2C_INDEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_maxtouch_controller, value: '0'}
  - type: Integer
    attributes: {id: Height}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_maxtouch_controller, value: '272'}
  - type: Boolean
    attributes: {id: RTOSEnabled}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Menu
    attributes: {id: RTOSMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TOUCH_DRV_RTOS_TASK_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: Width}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_maxtouch_controller, value: '480'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: i2c}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_i2c_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2c}
  - type: DirectDependency
    attributes: {id: touch_panel}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_disp_pdatm4301b_480x272}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: touch_panel}
- type: ElementPosition
  attributes: {x: '358', y: '168', id: gfx_maxtouch_controller}
