configName: pic32mzda_curiosity
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../Harmony_public_release
processor: PIC32MZ2064DAR176
projectName: ''
settings:
  PackageFilter: audio;bootloader;bootloader_apps_uart;bsp;bt;core;crypto;cryptoauthlib;cryptoauthlib_apps;csp;csp_apps_pic32cm_mc00;csp_apps_sam_c20_c21;csp_apps_sam_d21_da1;gfx;gfx_apps;gfx_apps_sam_d5x_e5x;net;net_apps_sam_e70_v71;reference_apps;touch;usb;wireless
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-DA_DFP\1.4.118\atdf\PIC32MZ2064DAR176.atdf
