format_version: v1.0
type: UniqueComponent
attributes: {id: uart4}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: '214'}
  - type: KeyValueSet
    attributes: {id: UART_BRGH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: '0'}
  - type: Comment
    attributes: {id: UART_BRGH_MODE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** High Speed mode 4x baud clock enabled (BRGH =
            1) ***'}
  - type: Integer
    attributes: {id: UART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: '99000000'}
  - type: Boolean
    attributes: {id: UART_RING_BUFFER_ENABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: 'false'}
  - type: Hex
    attributes: {id: UMODE_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart4, value: '8'}
  - type: Boolean
    attributes: {id: USART_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: stdio, value: 'false'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: UART4_UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: stdio}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: UART}
- type: ElementPosition
  attributes: {x: '0', y: '56', id: uart4}
