format_version: v1.0
type: UniqueComponent
attributes: {id: usb_host}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CONFIG_USB_HOST_TPL_ENTRY_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_host, value: '1'}
- type: ElementPosition
  attributes: {x: '0', y: '298', id: usb_host}
