format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_hal_le}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '96'}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '96'}
  - type: String
    attributes: {id: DriverName}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: LE External Controller}
  - type: Integer
    attributes: {id: RefreshRate}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_hal_le, value: '0'}
  - type: String
    attributes: {id: gfx_driver}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: le_gfx_driver_external}
- type: ElementPosition
  attributes: {x: '318', y: '11', id: gfx_hal_le}
