format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipHttpNet}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_HTTP_NET_CUSTOM_TEMPLATE_SL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipHttpNet, value: 'false'}
  - type: String
    attributes: {id: TCPIP_HTTP_NET_FREE_FUNC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: vPortFree}
  - type: Integer
    attributes: {id: TCPIP_HTTP_NET_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipHttpNet, value: '4944'}
  - type: String
    attributes: {id: TCPIP_HTTP_NET_MALLOC_FUNC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: pvPortMalloc}
  - type: Integer
    attributes: {id: TCPIP_HTTP_NET_SSI_VARIABLE_NAME_MAX_LENGTH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '20'}
  - type: Integer
    attributes: {id: TCPIP_HTTP_NET_SSI_VARIABLE_STRING_MAX_LENGTH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '20'}
  - type: String
    attributes: {id: TCPIP_HTTP_NET_WEBPAGE_DIRECTORY_PATH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'D:\MassMarket\harmony_github\net\web_pages'}
  - type: String
    attributes: {id: TCPIP_HTTP_NET_WEB_DIR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: /mnt/mchpSite1/web_pages}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE10}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE11}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE12}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE13}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE14}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE15}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE16}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE17}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE18}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE19}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE20}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE21}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE22}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE4}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE5}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE6}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE7}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE8}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE9}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '310', y: '140', id: tcpipHttpNet}
