format_version: v1.0
type: UniqueComponent
attributes: {id: tc3}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: SYS_TIME_COMPONENT_ID}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc3, value: sys_time}
  - type: String
    attributes: {id: SYS_TIME_PLIB_OPERATION_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc3, value: SYS_TIME_PLIB_MODE_COMPARE}
  - type: Comment
    attributes: {id: TC_COMPARE_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Compare Period is 0.5 us ****'}
  - type: KeyValueSet
    attributes: {id: TC_CTRLA_PRESCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: TC_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc3, value: '48000000'}
  - type: Comment
    attributes: {id: TC_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Timer resolution is 20.8333333333 nS****'}
  - type: Boolean
    attributes: {id: TC_SYS_TIME_CONNECTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc3, value: 'true'}
  - type: Boolean
    attributes: {id: TC_TIMER_INTENSET_MC1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc3, value: 'true'}
  - type: Boolean
    attributes: {id: TC_TIMER_INTENSET_OVF}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc3, value: 'false'}
  - type: Long
    attributes: {id: TC_TIMER_PERIOD}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc3, value: '48000'}
  - type: Float
    attributes: {id: TC_TIMER_TIME_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '1.3653333'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: TC3_TMR}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_time}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_time_TMR_dependency}
- type: ElementPosition
  attributes: {x: '167', y: '81', id: tc3}
