format_version: v1.0
type: UniqueComponent
attributes: {id: bluetooth_bm71}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_BM71_USART}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: bluetooth_bm71, value: SERCOM3_USART}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: USART PLIB}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom3}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM3_UART}
- type: ElementPosition
  attributes: {x: '740', y: '20', id: bluetooth_bm71}
