format_version: v1.0
type: UniqueComponent
attributes: {id: sercom3}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: I2CM_BAUD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom3, value: '232'}
  - type: String
    attributes: {id: RECEIVE_DATA_REGISTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom3, value: '&(SERCOM3_REGS->USART_INT.SERCOM_DATA)'}
  - type: KeyValueSet
    attributes: {id: SERCOM_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom3, value: '0'}
  - type: File
    attributes: {id: SERCOM_USART_COMMON_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: SERCOM_USART_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: SERCOM_USART_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: SPI_BAUD_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom3, value: '23'}
  - type: String
    attributes: {id: TRANSMIT_DATA_REGISTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom3, value: '&(SERCOM3_REGS->USART_INT.SERCOM_DATA)'}
  - type: Integer
    attributes: {id: USART_BAUD_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom3, value: '63019'}
  - type: KeyValueSet
    attributes: {id: USART_FORM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom3, value: '0'}
  - type: Boolean
    attributes: {id: USART_LIN_MASTER_SUPPORTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom3, value: 'true'}
  - type: KeyValueSet
    attributes: {id: USART_RXPO}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: Integer
    attributes: {id: USART_SAMPLE_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom3, value: '16'}
  - type: Integer
    attributes: {id: USART_SAMPLE_RATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom3, value: '0'}
  - type: KeyValueSet
    attributes: {id: USART_TXPO}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: SERCOM3_I2C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectCapability
    attributes: {id: SERCOM3_SPI}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectCapability
    attributes: {id: SERCOM3_UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: bluetooth_bm71}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: USART PLIB}
- type: ElementPosition
  attributes: {x: '600', y: '20', id: sercom3}
