format_version: v1.0
type: UniqueComponent
attributes: {id: stdio}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DEBUG_PERIPHERAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: stdio, value: sercom1}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom1}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM1_UART}
- type: ElementPosition
  attributes: {x: '159', y: '233', id: stdio}
