format_version: v1.0
type: UniqueComponent
attributes: {id: tc0}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: SYS_TIME_COMPONENT_ID}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: sys_time}
  - type: String
    attributes: {id: SYS_TIME_PLIB_OPERATION_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: SYS_TIME_PLIB_MODE_COMPARE}
  - type: Integer
    attributes: {id: TC_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '48000000'}
  - type: Boolean
    attributes: {id: TC_SYS_TIME_CONNECTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'true'}
  - type: Boolean
    attributes: {id: TC_TIMER_INTENSET_MC1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'true'}
  - type: Boolean
    attributes: {id: TC_TIMER_INTENSET_OVF}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
  - type: Long
    attributes: {id: TC_TIMER_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '48000'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: TC0_TMR}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_time}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_time_TMR_dependency}
- type: ElementPosition
  attributes: {x: '148', y: '293', id: tc0}
