format_version: v1.0
type: UniqueComponent
attributes: {id: twihs0}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TWIHS_CLK_SRC_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '150000000'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CHDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '177'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CKDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '0'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CLDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '192'}
  - type: Boolean
    attributes: {id: TWIHS_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: 'true'}
  - type: Combo
    attributes: {id: TWIHS_OPMODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: MASTER}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: TWIHS0_I2C}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_i2c_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2c_I2C_dependency}
- type: ElementPosition
  attributes: {x: '15', y: '197', id: twihs0}
