format_version: v1.0
type: UniqueComponent
attributes: {id: tc0}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ENCODER_POS_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: TC0_QuadraturePositionGet}
  - type: String
    attributes: {id: ENCODER_POS_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: ''}
  - type: String
    attributes: {id: ENCODER_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: TC0_QuadratureStart}
  - type: String
    attributes: {id: ENCODER_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: TC0_QuadratureStop}
  - type: Integer
    attributes: {id: TC0_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '1000'}
  - type: KeyValueSet
    attributes: {id: TC0_CMR_TCCLKS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: TC0_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TC0_PCK7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
  - type: Comment
    attributes: {id: TC0_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Clock resolution is 1000000.0 nS****'}
  - type: Comment
    attributes: {id: TC0_TIMER_PERIOD_CMT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Period Count is 500****'}
  - type: Long
    attributes: {id: TC0_TIMER_PERIOD_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '500'}
  - type: Float
    attributes: {id: TC0_TIMER_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '65536.0'}
    - type: Values
      children:
      - type: User
        attributes: {value: '500.0'}
  - type: Integer
    attributes: {id: TC1_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '150000000'}
  - type: Boolean
    attributes: {id: TC1_PCK7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
  - type: Comment
    attributes: {id: TC1_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Clock resolution is 6.66666666667 nS****'}
  - type: Comment
    attributes: {id: TC1_TIMER_PERIOD_CMT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Period Count is 60000****'}
  - type: Long
    attributes: {id: TC1_TIMER_PERIOD_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '60000'}
  - type: Integer
    attributes: {id: TC2_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '150000000'}
  - type: Boolean
    attributes: {id: TC2_PCK7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
  - type: Comment
    attributes: {id: TC2_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Clock resolution is 6.66666666667 nS****'}
  - type: Comment
    attributes: {id: TC2_TIMER_PERIOD_CMT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Period Count is 60000****'}
  - type: Long
    attributes: {id: TC2_TIMER_PERIOD_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '60000'}
  - type: Integer
    attributes: {id: TC3_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '1000'}
  - type: Boolean
    attributes: {id: TC3_PCK7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
  - type: Comment
    attributes: {id: TC3_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Clock resolution is 1000000.0 nS****'}
  - type: Combo
    attributes: {id: TC_PCK_CLKSRC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: TC_QEI_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Time Base is 15015000.0 uS****'}
- type: ElementPosition
  attributes: {x: '49', y: '76', id: tc0}
