format_version: v1.0
type: UniqueComponent
attributes: {id: eic}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: EIC_ASYNCH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '4'}
  - type: KeyValueSet
    attributes: {id: EIC_ASYNCH_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: EIC_CHAN_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: EIC_CLKSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: EIC_CONFIG_FILTEN_2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: EIC_CONFIG_SENSE_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Hex
    attributes: {id: EIC_EXTINTEO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '0'}
  - type: Hex
    attributes: {id: EIC_INT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '4'}
  - type: Boolean
    attributes: {id: EIC_INT_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Menu
    attributes: {id: EIC_MENU2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '170', y: '80', id: eic}
