configName: SAMD21_WG_IOT
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../Harmony_public_release
processor: ATSAMD21G18A
projectName: ''
settings:
  PackageFilter: audio;bootloader;bootloader_apps_uart;bsp;bt;core;crypto;csp;csp_apps_pic32cm_mc00;csp_apps_sam_c20_c21;gfx;gfx_apps;gfx_apps_pic32mz_da;net;touch;usb;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.4.104\samd21a\atdf\ATSAMD21G18A.atdf
