configName: pic32mz_ef_curiosity_v2
folderName: ''
format_version: v1.0
frameworkPath: D:\Projects\git_hub
processor: PIC32MZ2048EFM144
projectName: ''
settings:
  PackageFilter: audio;bsp;bt;core;core_apps_sam_e70_s70_v70_v71;crypto;cryptoauthlib;csp;dev_packs;gfx;gfx_apps;quick_docs;reference_apps;usb;wireless_apps_winc1500;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFM144.atdf
