format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_sdspi}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_SDSPI_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sdspi, value: Asynchronous}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_sdspi}
    children:
    - type: Symbols
      children:
      - type: File
        attributes: {id: DRV_SDSPI_ASYNC_PLIB_INTERFACE_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: File
        attributes: {id: DRV_SDSPI_ASYNC_PLIB_INTERFACE_SOURCE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: KeyValueSet
        attributes: {id: DRV_SDSPI_CHIP_SELECT_PIN}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '29'}
      - type: String
        attributes: {id: DRV_SDSPI_INTERFACE_TYPE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: SPI_PLIB}
      - type: String
        attributes: {id: DRV_SDSPI_PLIB}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: SPI2}
      - type: Integer
        attributes: {id: DRV_SDSPI_QUEUE_SIZE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '10'}
      - type: Menu
        attributes: {id: DRV_SDSPI_RTOS_MENU}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
      - type: Integer
        attributes: {id: DRV_SDSPI_RX_DMA_CHANNEL}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: '1'}
      - type: Integer
        attributes: {id: DRV_SDSPI_SPEED_HZ}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '25000000'}
      - type: Integer
        attributes: {id: DRV_SDSPI_TX_DMA_CHANNEL}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: '0'}
      - type: Boolean
        attributes: {id: DRV_SDSPI_TX_RX_DMA}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: readOnly}
            children:
            - {type: Value, value: 'false'}
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
        - type: Values
          children:
          - type: User
            attributes: {value: 'true'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_sdspi_SPI_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: spi2}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: SPI2_SPI}
- type: ElementPosition
  attributes: {x: '232', y: '314', id: drv_sdspi}
