format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_driver_external}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: Command0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '175'}
  - type: String
    attributes: {id: Command0Comment}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Make display ON}
  - type: Integer
    attributes: {id: Command0Delay}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '200'}
  - type: Hex
    attributes: {id: Command1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '160'}
  - type: String
    attributes: {id: Command1Comment}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SET_REMAP_DUAL_COM_LINE_COMMAND}
  - type: Hex
    attributes: {id: Command1Parm0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '50'}
  - type: Integer
    attributes: {id: Command1ParmsCount}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Hex
    attributes: {id: Command2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '161'}
  - type: String
    attributes: {id: Command2Comment}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SET_DISPLAY_START_LINE_COMMAND}
  - type: Hex
    attributes: {id: Command2Parm0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '32'}
  - type: Integer
    attributes: {id: Command2ParmsCount}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: String
    attributes: {id: ControllerName}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SSD1351}
  - type: Combo
    attributes: {id: DataWriteSize}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '8'}
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '96'}
  - type: Combo
    attributes: {id: DisplayInterfaceType}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SPI 4-line}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '96'}
  - type: Combo
    attributes: {id: FrameAddressSize}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 1-byte}
  - type: Hex
    attributes: {id: MemoryWriteCommand}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '92'}
  - type: Comment
    attributes: {id: PixelDataInfoString16bit}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: PixelDataInfoString8bit2byteNorm}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: PixelDataTxSize8Bit}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: PostResetDelay}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: ResetAssertDuration}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Hex
    attributes: {id: SetXAddressCommand}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '21'}
  - type: Menu
    attributes: {id: SetXAddressParmMenuByte}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: SetXAddressParmMenuWord}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Hex
    attributes: {id: SetYAddressCommand}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '117'}
  - type: Menu
    attributes: {id: SetYAddressParmMenuByte}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: SetYAddressParmMenuWord}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: XAddressOffset}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '16'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: Parallel Display Interface}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectDependency
    attributes: {id: SPI Display Interface}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_intf_spi4}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: le_gfx_intf_spi4}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: DirectCapability
    attributes: {id: gfx_driver_external}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_legato}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_driver}
- type: ElementPosition
  attributes: {x: '540', y: '20', id: le_gfx_driver_external}
