format_version: v1.0
type: UniqueComponent
attributes: {id: HarmonyCore}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: APP0_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: APP0_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: COMMON_SYMBOL_CNTR}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: 'TRUE', value: '0', key: ENABLE_DRV_COMMON}
          - type: Pair
            attributes: {description: 'TRUE', value: '0', key: ENABLE_SYS_COMMON}
          - type: Pair
            attributes: {description: 'FALSE', value: '0', key: ENABLE_SYS_MEDIA}
          - type: Pair
            attributes: {description: 'TRUE', value: '0', key: ENABLE_SYS_PORTS}
          - type: Pair
            attributes: {description: 'TRUE', value: '0', key: ENABLE_SYS_DMA}
          - type: Pair
            attributes: {description: 'FALSE', value: '0', key: ENABLE_SYS_RESET}
  - type: Boolean
    attributes: {id: ENABLE_APP_FILE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_DRV_COMMON}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'false'}
  - type: Boolean
    attributes: {id: ENABLE_OSAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_SYS_CACHE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_SYS_COMMON}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_SYS_DMA}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'false'}
  - type: Boolean
    attributes: {id: ENABLE_SYS_INT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_SYS_PORTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'false'}
  - type: File
    attributes: {id: SYS_CACHE_DEF}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: SYS_CACHE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: SYS_CACHE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '7', y: '92', id: HarmonyCore}
