configName: sam_e51_cnano
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../Projects/git_hub
processor: ATSAME51J20A
projectName: ''
settings:
  PackageFilter: audio;bsp;bt;core;cryptoauthlib;csp;gfx;gfx_apps;usb;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME51_DFP\3.3.78\atdf\ATSAME51J20A.atdf
