format_version: v1.0
type: GroupComponent
attributes: {displayName: TCP/IP STACK, id: TCP/IP STACK}
children:
- type: ElementPosition
  attributes: {x: '367', y: '89', id: TCP/IP STACK}
- type: Attachments
  children:
  - type: Attachment
    attributes: {targetComponentID: lib_wolfssl, namespace: PRESENTATION LAYER, id: 'net_Pres:Net_Pres_Crypto_Dependency',
      targetAttachmentID: lib_wolfssl}
  - type: Attachment
    attributes: {targetComponentID: sys_console_0, namespace: BASIC CONFIGURATION,
      id: 'tcpipStack:Core_SysConsole_Dependency', targetAttachmentID: sys_console}
