format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_i2c}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_I2C_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_i2c, value: Asynchronous}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_i2c}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_I2C_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_i2c_0, value: I2C2}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: drv_i2c}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: gfx_generic_touch_controller}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: i2c}
      - type: DirectDependency
        attributes: {id: drv_i2c_I2C_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: i2c2}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: I2C2_I2C}
- type: ElementPosition
  attributes: {x: '303', y: '150', id: drv_i2c}
