format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_sdspi}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DRV_SDSPI_COMMON_FS_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sdspi, value: 'true'}
  - type: Combo
    attributes: {id: DRV_SDSPI_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sdspi, value: Asynchronous}
  - type: Integer
    attributes: {id: DRV_SDSPI_COMMON_SPI_DRV_INSTANCE_CNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sdspi, value: '1'}
  - type: File
    attributes: {id: DRV_SDSPI_FS_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_sdspi}
    children:
    - type: Symbols
      children:
      - type: File
        attributes: {id: DRV_SDSPI_ASYNC_DRIVER_INTERFACE_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: File
        attributes: {id: DRV_SDSPI_ASYNC_DRIVER_INTERFACE_SOURCE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: KeyValueSet
        attributes: {id: DRV_SDSPI_CHIP_SELECT_PIN}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '49'}
      - type: Boolean
        attributes: {id: DRV_SDSPI_FS_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: 'true'}
      - type: String
        attributes: {id: DRV_SDSPI_INTERFACE_TYPE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: SPI_DRV}
      - type: Integer
        attributes: {id: DRV_SDSPI_NUM_CLIENTS}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '2'}
      - type: Menu
        attributes: {id: DRV_SDSPI_RTOS_MENU}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
      - type: String
        attributes: {id: DRV_SDSPI_SPI_DRIVER_INSTANCE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: '0'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_sdspi_DRV_SPI_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: drv_spi_0}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: drv_spi}
- type: ElementPosition
  attributes: {x: '289', y: '228', id: drv_sdspi}
