format_version: v1.0
type: UniqueComponent
attributes: {id: evsys}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: EVSYS_CHANNEL_0_GENERATOR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '28'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_0_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'true'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_0_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'true'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_10_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_10_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_11_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_11_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_1_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_1_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_2_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_2_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_3_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_3_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_4_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_4_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_5_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_5_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_6_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_6_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_7_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_7_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_8_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_8_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_9_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_9_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Menu
    attributes: {id: EVSYS_MENU_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: EVSYS_USER_25}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: GENERATOR_AC_COMP_0_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ac, value: 'false'}
  - type: Boolean
    attributes: {id: GENERATOR_DMAC_CH_0_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: GENERATOR_EIC_EXTINT_15_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: 'true'}
  - type: Boolean
    attributes: {id: GENERATOR_RTC_CMP_0_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: 'true'}
  - type: Boolean
    attributes: {id: USER_AC_SOC_0_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ac, value: 'true'}
  - type: Boolean
    attributes: {id: USER_DMAC_CH_0_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
- type: ElementPosition
  attributes: {x: '159', y: '36', id: evsys}
