format_version: v1.0
type: UniqueComponent
attributes: {id: sercom4}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: I2CM_BAUD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom4, value: '255'}
  - type: Integer
    attributes: {id: I2CS_SDASETUP_TIME_NS}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '2050'}
  - type: Integer
    attributes: {id: I2CS_SDASETUP_TIME_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom4, value: '1'}
  - type: Boolean
    attributes: {id: I2CS_SDASETUP_TIME_SUPPORT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom4, value: 'true'}
  - type: Integer
    attributes: {id: SPI_BAUD_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom4, value: '29'}
  - type: Integer
    attributes: {id: USART_BAUD_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom4, value: '63522'}
  - type: KeyValueSet
    attributes: {id: USART_FORM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom4, value: '0'}
  - type: Boolean
    attributes: {id: USART_LIN_MASTER_SUPPORTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom4, value: 'true'}
  - type: KeyValueSet
    attributes: {id: USART_RXPO}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: USART_SAMPLE_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom4, value: '16'}
  - type: Integer
    attributes: {id: USART_SAMPLE_RATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom4, value: '0'}
- type: ElementPosition
  attributes: {x: '417', y: '17', id: sercom4}
