format_version: v1.0
type: UniqueComponent
attributes: {id: rtc}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: RTC_MODE0_EVCTRL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '256'}
  - type: Boolean
    attributes: {id: RTC_MODE0_EVCTRL_CMPEO0_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: RTC_MODE0_INTERRUPT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: RTC_MODE0_MATCHCLR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Hex
    attributes: {id: RTC_MODE0_TIMER_COMPARE0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '327'}
  - type: Hex
    attributes: {id: RTC_MODE0_TIMER_COMPARE1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
- type: ElementPosition
  attributes: {x: '166', y: '227', id: rtc}
