format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipStack}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_STACK_DRAM_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '76960'}
  - type: Integer
    attributes: {id: TCPIP_STACK_HEAP_SIZE_RECOMMEND}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: '58'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_INTERFACE_CHANGE_SIGNALING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_INTERRUPT_EN_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_INT_MAC_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_STACK_MAC_CLOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: '120000000'}
  - type: String
    attributes: {id: TCPIP_STACK_MII_MODE_IDX0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: RMII}
  - type: String
    attributes: {id: TCPIP_STACK_NET_INTERFACE_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: GMAC}
  - type: Menu
    attributes: {id: TCPIP_STACK_RTOS_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_SYS_RANDOM_H2_ADAPTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: 'true'}
  - type: File
    attributes: {id: TCPIP_SYS_RTOS_TASK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '240', y: '20', id: tcpipStack}
