format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_E54_Curiosity_Ultra, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '0', y: '45', id: BSP_SAM_E54_Curiosity_Ultra}
