format_version: v1.0
type: UniqueComponent
attributes: {id: sercom5}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: I2CM_BAUD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: '255'}
  - type: Integer
    attributes: {id: I2CS_SDASETUP_TIME_NS}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '2050'}
  - type: Integer
    attributes: {id: I2CS_SDASETUP_TIME_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: '1'}
  - type: Boolean
    attributes: {id: I2CS_SDASETUP_TIME_SUPPORT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: 'true'}
  - type: Integer
    attributes: {id: SPI_BAUD_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: '29'}
  - type: Integer
    attributes: {id: USART_BAUD_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: '63522'}
  - type: KeyValueSet
    attributes: {id: USART_FORM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: '0'}
  - type: Boolean
    attributes: {id: USART_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: USART_INTERRUPT_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: 'false'}
  - type: Boolean
    attributes: {id: USART_LIN_MASTER_SUPPORTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: 'true'}
  - type: KeyValueSet
    attributes: {id: USART_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: '0'}
  - type: Boolean
    attributes: {id: USART_RING_BUFFER_ENABLE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: 'false'}
  - type: Boolean
    attributes: {id: USART_RING_BUFFER_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: 'false'}
  - type: KeyValueSet
    attributes: {id: USART_RXPO}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: USART_RX_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: USART_SAMPLE_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: '16'}
  - type: Integer
    attributes: {id: USART_SAMPLE_RATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom5, value: '0'}
- type: ElementPosition
  attributes: {x: '330', y: '100', id: sercom5}
