format_version: v1.0
type: UniqueComponent
attributes: {id: eic}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: EIC_ASYNCH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '1024'}
  - type: KeyValueSet
    attributes: {id: EIC_ASYNCH_10}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: EIC_CHAN_10}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: EIC_CONFIG_FILTEN_10}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: EIC_CONFIG_SENSE_10}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Hex
    attributes: {id: EIC_EXTINTEO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '0'}
  - type: Hex
    attributes: {id: EIC_INT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '1024'}
  - type: Boolean
    attributes: {id: EIC_INT_10}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Menu
    attributes: {id: EIC_MENU10}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '13', y: '219', id: eic}
