configName: pic32cm_mc00_cnano
folderName: pic32cm_mc00_cnano
format_version: v1.0
frameworkPath: ../../../../../Projects/git_hub
processor: PIC32CM1216MC00032
projectName: smart_tag_demo_pic32cm_mc00_cnano
settings:
  PackageFilter: audio;bsp;bt;core;core_apps_sam_e70_s70_v70_v71;crypto;cryptoauthlib;csp;gfx;gfx_apps;reference_apps;usb;wireless_apps_winc1500;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-MC_DFP\1.2.52\PIC32CM1216MC00032\atdf\PIC32CM1216MC00032.atdf
