files:
- generatedChecksum: 9762B12622FD08815784244AF2080753
  logicalPath: config\sam_d21_cnano
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9762B12622FD08815784244AF2080753
- generatedChecksum: ABB2786191CC2C0E43741F3947BAA7D9
  logicalPath: config\sam_d21_cnano
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: ABB2786191CC2C0E43741F3947BAA7D9
- generatedChecksum: 2CE0189B5EE789F64C343FFCA9A358FF
  logicalPath: config\sam_d21_cnano
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2CE0189B5EE789F64C343FFCA9A358FF
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config\sam_d21_cnano
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 13E8C342C46A3C7CBBA0655DCD13B7CB
  logicalPath: config\sam_d21_cnano\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13E8C342C46A3C7CBBA0655DCD13B7CB
- generatedChecksum: A4DF2C7CCA06FF336A4486F20F27A3E9
  logicalPath: config\sam_d21_cnano\peripheral\dmac
  name: plib_dmac.c
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: A4DF2C7CCA06FF336A4486F20F27A3E9
- generatedChecksum: 9B83CE6C4436A6B67A9E63C4A0041104
  logicalPath: config\sam_d21_cnano\peripheral\eic
  name: plib_eic.c
  physicalPath: peripheral\eic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9B83CE6C4436A6B67A9E63C4A0041104
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\sam_d21_cnano\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: F9B41ECBBFE623335C95C8BA63B3637B
  logicalPath: config\sam_d21_cnano\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: F9B41ECBBFE623335C95C8BA63B3637B
- generatedChecksum: 755CE0744FD3F0406718F83A3D9809FA
  logicalPath: config\sam_d21_cnano\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: 755CE0744FD3F0406718F83A3D9809FA
- generatedChecksum: 07710DAA46F2E3695643D97730BF7E70
  logicalPath: config\sam_d21_cnano\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: 07710DAA46F2E3695643D97730BF7E70
- generatedChecksum: DC10813824D37445F399594247F7E53A
  logicalPath: config\sam_d21_cnano\peripheral\sercom\spi_master
  name: plib_sercom1_spi_master.c
  physicalPath: peripheral\sercom\spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: DC10813824D37445F399594247F7E53A
- generatedChecksum: 452EAC29ABB6ED99ECB93F8AE5570774
  logicalPath: config\sam_d21_cnano\peripheral\sercom\usart
  name: plib_sercom5_usart.c
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 452EAC29ABB6ED99ECB93F8AE5570774
- generatedChecksum: 4E52725DF4CA8F9BD73F502693CB9E32
  logicalPath: config\sam_d21_cnano\peripheral\systick
  name: plib_systick.c
  physicalPath: peripheral\systick
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4E52725DF4CA8F9BD73F502693CB9E32
- generatedChecksum: 949BBD944EC8B81E639121B72E7C7510
  logicalPath: config\sam_d21_cnano
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 949BBD944EC8B81E639121B72E7C7510
- generatedChecksum: 2A06DFCC116BD1E069364EAD5B0AC9E5
  logicalPath: config\sam_d21_cnano\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2A06DFCC116BD1E069364EAD5B0AC9E5
- generatedChecksum: 96EAE00325275AE02509AD61BA1B6A14
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 96EAE00325275AE02509AD61BA1B6A14
- generatedChecksum: 41E2C84816B3163741E719D60CF7F0ED
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 41E2C84816B3163741E719D60CF7F0ED
- generatedChecksum: 9A226A0F5E36C8E55674FB8CF59961C5
  logicalPath: packs\ATSAMD21G17D_DFP
  name: atsamd21g17d.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 9A226A0F5E36C8E55674FB8CF59961C5
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: CCBD23918BE14943EA128B0D552031C5
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm0plus.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: CCBD23918BE14943EA128B0D552031C5
- generatedChecksum: D67B623A08ADCF5522C7EC00AC65883A
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D67B623A08ADCF5522C7EC00AC65883A
- generatedChecksum: 5E79A1BEBBF173FEB06D73EFA2F0E7EC
  logicalPath: config\sam_d21_cnano
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5E79A1BEBBF173FEB06D73EFA2F0E7EC
- generatedChecksum: 8F6AC76AEA7E712A46E31152B07BFFCA
  logicalPath: config\sam_d21_cnano
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 8F6AC76AEA7E712A46E31152B07BFFCA
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_d21_cnano
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: B436033DC5C7207672F7FA3C07D994B4
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B436033DC5C7207672F7FA3C07D994B4
- generatedChecksum: 44FB069E5C3BAA19C77B7297ED0E8BAC
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 44FB069E5C3BAA19C77B7297ED0E8BAC
- generatedChecksum: 6442C2801B5FD4F05B55FAFD2021A4BF
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6442C2801B5FD4F05B55FAFD2021A4BF
- generatedChecksum: C2078ADA4BEE2AABC1C7B281DFBA659B
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C2078ADA4BEE2AABC1C7B281DFBA659B
- generatedChecksum: 01D265DEB406571047698C8A52EC76BF
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 01D265DEB406571047698C8A52EC76BF
- generatedChecksum: 38ED6A06C9B8ADA3C2709AF9332BDAF5
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: hmatrixb.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 38ED6A06C9B8ADA3C2709AF9332BDAF5
- generatedChecksum: 30764463952C4DCB112717A483952818
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: i2s.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 30764463952C4DCB112717A483952818
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: 7D41187EB922B68CA2678CFBE354CE46
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7D41187EB922B68CA2678CFBE354CE46
- generatedChecksum: D84B4EDF3EDD24A730E02898DA3F3807
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D84B4EDF3EDD24A730E02898DA3F3807
- generatedChecksum: 08BC8D3013F6D2EED390B6BC914A38EF
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 08BC8D3013F6D2EED390B6BC914A38EF
- generatedChecksum: C591D09F115E12D00921D14939E3900D
  logicalPath: config\sam_d21_cnano\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: C591D09F115E12D00921D14939E3900D
- generatedChecksum: 3A89E54D5A5E63233B53B023386895F1
  logicalPath: config\sam_d21_cnano\peripheral\dmac
  name: plib_dmac.h
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: 3A89E54D5A5E63233B53B023386895F1
- generatedChecksum: 65A7F4C1E82078896D6BC6C3BB44F804
  logicalPath: config\sam_d21_cnano\peripheral\eic
  name: plib_eic.h
  physicalPath: peripheral\eic
  security: NON_SECURE
  type: HEADER
  userChecksum: 65A7F4C1E82078896D6BC6C3BB44F804
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_d21_cnano\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config\sam_d21_cnano\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: E06C4F1DF628200A4228C05DCFBF5A13
  logicalPath: config\sam_d21_cnano\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: E06C4F1DF628200A4228C05DCFBF5A13
- generatedChecksum: 6FFC4980ACD4BE6E1BD78B632FB370D0
  logicalPath: config\sam_d21_cnano\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: 6FFC4980ACD4BE6E1BD78B632FB370D0
- generatedChecksum: D3278D84519FC15D8D2EB14921A9BBFE
  logicalPath: config\sam_d21_cnano\peripheral\sercom\spi_master
  name: plib_sercom1_spi_master.h
  physicalPath: peripheral\sercom\spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: D3278D84519FC15D8D2EB14921A9BBFE
- generatedChecksum: 50E4F02F3767097B441D2DD6A0CADBEE
  logicalPath: config\sam_d21_cnano\peripheral\sercom\usart
  name: plib_sercom5_usart.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 50E4F02F3767097B441D2DD6A0CADBEE
- generatedChecksum: A06CFE6AEC7B18A5C3DEAC185207002C
  logicalPath: config\sam_d21_cnano\peripheral\sercom\spi_master
  name: plib_sercom_spi_master_common.h
  physicalPath: peripheral\sercom\spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: A06CFE6AEC7B18A5C3DEAC185207002C
- generatedChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
  logicalPath: config\sam_d21_cnano\peripheral\sercom\usart
  name: plib_sercom_usart_common.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
- generatedChecksum: 136B47BF2212B7E396B7BC40F05A89AE
  logicalPath: config\sam_d21_cnano\peripheral\systick
  name: plib_systick.h
  physicalPath: peripheral\systick
  security: NON_SECURE
  type: HEADER
  userChecksum: 136B47BF2212B7E396B7BC40F05A89AE
- generatedChecksum: 7513D9544A6BB2D4207A76FD624F9271
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7513D9544A6BB2D4207A76FD624F9271
- generatedChecksum: 5D5810211760CBCFC082BC3569B12563
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5810211760CBCFC082BC3569B12563
- generatedChecksum: 085D8DD71391A06324BE53DBB74B680C
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 085D8DD71391A06324BE53DBB74B680C
- generatedChecksum: 3F647FFC08E7732FDE36B256FEFE06E4
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 3F647FFC08E7732FDE36B256FEFE06E4
- generatedChecksum: 9E5319FA485909FA4EECF660ECB1AA33
  logicalPath: packs\ATSAMD21G17D_DFP\pio
  name: samd21g17d.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 9E5319FA485909FA4EECF660ECB1AA33
- generatedChecksum: FDF92F757BE32F136F90612465724743
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FDF92F757BE32F136F90612465724743
- generatedChecksum: 9288444A1AC70677A2F1717955488299
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: sysctrl.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9288444A1AC70677A2F1717955488299
- generatedChecksum: 8DD481B1E936F2B57D9BB5F3EE4DA080
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 8DD481B1E936F2B57D9BB5F3EE4DA080
- generatedChecksum: 00EE553FDE05AAD50C48374D650DE9F4
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 00EE553FDE05AAD50C48374D650DE9F4
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_d21_cnano
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 879748098838DE1510892277479EBBE4
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: usb.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 879748098838DE1510892277479EBBE4
- generatedChecksum: 64168781C7B6612173C1C51636CB25D3
  logicalPath: packs\ATSAMD21G17D_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMD21G17D_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 64168781C7B6612173C1C51636CB25D3
- generatedChecksum: EE81ADD481D77A1CF30C6F53FF90F015
  logicalPath: config\sam_d21_cnano
  name: ATSAMD21G17D.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: EE81ADD481D77A1CF30C6F53FF90F015
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d21_cnano;../src/packs/ATSAMD21G17D_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d21_cnano;../src/packs/ATSAMD21G17D_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
