format_version: v1.0
type: UniqueComponent
attributes: {id: uart6}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart6, value: '129'}
  - type: KeyValueSet
    attributes: {id: UART_BRGH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart6, value: '0'}
  - type: Comment
    attributes: {id: UART_BRGH_MODE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** High Speed mode 4x baud clock enabled (BRGH =
            1) ***'}
  - type: Integer
    attributes: {id: UART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart6, value: '60000000'}
  - type: Boolean
    attributes: {id: UART_INTERRUPT_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart6, value: 'false'}
  - type: Comment
    attributes: {id: UART_INTRRUPT_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: UART_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart6, value: '0'}
  - type: Boolean
    attributes: {id: UART_RING_BUFFER_ENABLE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart6, value: 'false'}
  - type: Boolean
    attributes: {id: UART_RING_BUFFER_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart6, value: 'false'}
  - type: Hex
    attributes: {id: UMODE_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart6, value: '8'}
  - type: Boolean
    attributes: {id: USART_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '33', y: '157', id: uart6}
